# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(579, 405)
        Form.setAutoFillBackground(True)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.eyepieceRadBtn = QtWidgets.QRadioButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eyepieceRadBtn.sizePolicy().hasHeightForWidth())
        self.eyepieceRadBtn.setSizePolicy(sizePolicy)
        self.eyepieceRadBtn.setObjectName("eyepieceRadBtn")
        self.gridLayout_4.addWidget(self.eyepieceRadBtn, 0, 0, 1, 1)
        self.cameraRadBtn = QtWidgets.QRadioButton(Form)
        self.cameraRadBtn.setObjectName("cameraRadBtn")
        self.gridLayout_4.addWidget(self.cameraRadBtn, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.loadMicroscopeBtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadMicroscopeBtn.sizePolicy().hasHeightForWidth())
        self.loadMicroscopeBtn.setSizePolicy(sizePolicy)
        self.loadMicroscopeBtn.setObjectName("loadMicroscopeBtn")
        self.gridLayout_2.addWidget(self.loadMicroscopeBtn, 0, 0, 1, 1)
        self.unloadBtn = QtWidgets.QPushButton(Form)
        self.unloadBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unloadBtn.sizePolicy().hasHeightForWidth())
        self.unloadBtn.setSizePolicy(sizePolicy)
        self.unloadBtn.setObjectName("unloadBtn")
        self.gridLayout_2.addWidget(self.unloadBtn, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.liveToggleBtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.liveToggleBtn.sizePolicy().hasHeightForWidth())
        self.liveToggleBtn.setSizePolicy(sizePolicy)
        self.liveToggleBtn.setObjectName("liveToggleBtn")
        self.gridLayout_3.addWidget(self.liveToggleBtn, 0, 0, 1, 1)
        self.snapshotBtn = QtWidgets.QPushButton(Form)
        self.snapshotBtn.setObjectName("snapshotBtn")
        self.gridLayout_3.addWidget(self.snapshotBtn, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.epiToggleBtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.epiToggleBtn.sizePolicy().hasHeightForWidth())
        self.epiToggleBtn.setSizePolicy(sizePolicy)
        self.epiToggleBtn.setObjectName("epiToggleBtn")
        self.gridLayout_5.addWidget(self.epiToggleBtn, 0, 0, 1, 1)
        self.diaToggleBtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diaToggleBtn.sizePolicy().hasHeightForWidth())
        self.diaToggleBtn.setSizePolicy(sizePolicy)
        self.diaToggleBtn.setObjectName("diaToggleBtn")
        self.gridLayout_5.addWidget(self.diaToggleBtn, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 5, 0, 2, 1)
        self.widget = MplWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 1, 8, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "deepthought"))
        self.eyepieceRadBtn.setText(_translate("Form", "Eye Piece"))
        self.cameraRadBtn.setText(_translate("Form", "Camera"))
        self.loadMicroscopeBtn.setText(_translate("Form", "Load Microscope"))
        self.unloadBtn.setText(_translate("Form", "Unload"))
        self.liveToggleBtn.setText(_translate("Form", "Live"))
        self.snapshotBtn.setText(_translate("Form", "Snap"))
        self.epiToggleBtn.setText(_translate("Form", "EPI"))
        self.diaToggleBtn.setText(_translate("Form", "DIA"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

